name: Server Stats CI/CD

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x server-stats.sh

      - name: Run script
        run: ./server-stats.sh

      - name: Build Docker image
        run: docker build -t server-stats .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Tag Docker image
        run: docker tag server-stats ${{ secrets.DOCKER_USER }}/server-stats:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/server-stats:latest
